package com.djcao.boot.repository;
// Generated 2019-7-13 10:24:46 by Hibernate Tools 5.2.8.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RegisterUserGroup generated by hbm2java
 */
@Entity
@Table(name="register_user_group"
    ,catalog="sneakerlover"
)
public class RegisterUserGroup  implements java.io.Serializable {


     private Long id;
     private Date createTime;
     private String groupName;
     private Date updateTime;
     private Long userId;

    public RegisterUserGroup() {
    }

    public RegisterUserGroup(Date createTime, String groupName, Date updateTime, Long userId) {
       this.createTime = createTime;
       this.groupName = groupName;
       this.updateTime = updateTime;
       this.userId = userId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="group_name")
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_time", length=19)
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    
    @Column(name="user_id")
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }




}


