package com.djcao.boot.repository;
// Generated 2019-7-6 18:25:48 by Hibernate Tools 5.2.8.Final


import java.util.Date;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * ShoesItem generated by hbm2java
 */
@Entity
@Table(name="shoes_item"
    ,catalog="sneakerlover"
)
public class ShoesItem  implements java.io.Serializable {


     private long id;
     private String name;
     private String model;
     private String image;
     private String registerNum;
     private Byte isSize;
     private String shoeSize;
     private String shop;
     private Date createTime;
     private Date updateTime;

    public ShoesItem() {
    }

	
    public ShoesItem(long id) {
        this.id = id;
    }
    public ShoesItem(long id, String name, String model, String image, String registerNum, Byte isSize, String shoeSize, String shop, Date createTime, Date updateTime) {
       this.id = id;
       this.name = name;
       this.model = model;
       this.image = image;
       this.registerNum = registerNum;
       this.isSize = isSize;
       this.shoeSize = shoeSize;
       this.shop = shop;
       this.createTime = createTime;
       this.updateTime = updateTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="model")
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }

    
    @Column(name="image")
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

    
    @Column(name="register_num")
    public String getRegisterNum() {
        return this.registerNum;
    }
    
    public void setRegisterNum(String registerNum) {
        this.registerNum = registerNum;
    }

    
    @Column(name="is_size")
    public Byte getIsSize() {
        return this.isSize;
    }
    
    public void setIsSize(Byte isSize) {
        this.isSize = isSize;
    }

    
    @Column(name="shoe_size")
    public String getShoeSize() {
        return this.shoeSize;
    }
    
    public void setShoeSize(String shoeSize) {
        this.shoeSize = shoeSize;
    }

    
    @Column(name="shop")
    public String getShop() {
        return this.shop;
    }
    
    public void setShop(String shop) {
        this.shop = shop;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_time", length=19)
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }




}


