package com.djcao.boot.repository;
// Generated 2019-7-20 19:50:45 by Hibernate Tools 5.2.8.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShoesItem generated by hbm2java
 */
@Entity
@Table(name="shoes_item"
    ,catalog="sneakerlover"
)
public class ShoesItem  implements java.io.Serializable {


     private Long id;
     private String brand;
     private Date createTime;
     private String image;
     private Byte isSize;
     private String itemId;
     private String model;
     private String name;
     private String registerNum;
     private String shoeSize;
     private String shop;
     private Byte status;
     private Date updateTime;
     private String city;

    public ShoesItem() {
    }

    public ShoesItem(String brand, Date createTime, String image, Byte isSize, String itemId, String model, String name, String registerNum, String shoeSize, String shop, Byte status, Date updateTime, String city) {
       this.brand = brand;
       this.createTime = createTime;
       this.image = image;
       this.isSize = isSize;
       this.itemId = itemId;
       this.model = model;
       this.name = name;
       this.registerNum = registerNum;
       this.shoeSize = shoeSize;
       this.shop = shop;
       this.status = status;
       this.updateTime = updateTime;
       this.city = city;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="brand", length=20)
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="image")
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

    
    @Column(name="is_size")
    public Byte getIsSize() {
        return this.isSize;
    }
    
    public void setIsSize(Byte isSize) {
        this.isSize = isSize;
    }

    
    @Column(name="item_id", length=20)
    public String getItemId() {
        return this.itemId;
    }
    
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    
    @Column(name="model")
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="register_num")
    public String getRegisterNum() {
        return this.registerNum;
    }
    
    public void setRegisterNum(String registerNum) {
        this.registerNum = registerNum;
    }

    
    @Column(name="shoe_size")
    public String getShoeSize() {
        return this.shoeSize;
    }
    
    public void setShoeSize(String shoeSize) {
        this.shoeSize = shoeSize;
    }

    
    @Column(name="shop")
    public String getShop() {
        return this.shop;
    }
    
    public void setShop(String shop) {
        this.shop = shop;
    }

    
    @Column(name="status")
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_time", length=19)
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    
    @Column(name="city", length=40)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }




}


